auth_users/urls.py
from django.urls import path

from .views import (
    LoginView, RegisterView
)

app_name = "auth_users"
urlpatterns = [
    path("register/", RegisterView.as_view(), name="register"),
    path("login/", LoginView.as_view(), name="login")
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("authentication/", include("auth_users.urls")),
    path("", include("home.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from .views import (
    HomeView, ProfileView, RecentView, AllFilesView, ImageFilesView,
    VideoFilesView, FolderDetailView, AllFoldersView, ComparePlansView
)

app_name = "home"
urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("profile/", ProfileView.as_view(), name="profile"),
    path("recent/", RecentView.as_view(), name="recent"),
    path("file/all/", AllFilesView.as_view(), name="all-files"),
    path("folder/all/", AllFoldersView.as_view(), name="all-folders"),
    path("image/all/", ImageFilesView.as_view(), name="all-images"),
    path("video/all/", VideoFilesView.as_view(), name="all-videos"),
    path("folder/<str:folder_slug>/", FolderDetailView.as_view(), name="folder-details"),
    path("compare-plans/", ComparePlansView.as_view(), name="compare-plans")
]

auth_users/models.py
from django.db import models
from django.utils import timezone
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser
import shortuuid


class UserManager(BaseUserManager):
    def create_user(self, email, username, password=None):
        if not email:
            return ValueError("Email field is required!")
        elif not username:
            return ValueError("Username field is required!")

        email = self.normalize_email(email)

        user = self.model(email=email, username=username)
        user.set_password(password)
        user.save()

    def create_superuser(self, email, username, password=None):
        if not email:
            return ValueError("Email field is required!")
        elif not username:
            return ValueError("Username field is required!")

        email = self.normalize_email(email)

        user = self.model(email=email, username=username)
        user.set_password(password)
        user.is_staff = True
        user.is_superuser = True
        user.is_verified = True
        user.save()


class User(AbstractBaseUser):
    slug = models.SlugField(max_length=120, null=True, blank=True)
    username = models.CharField(max_length=120)
    email = models.EmailField(unique=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    is_ban = models.BooleanField(default=False)
    ban_reason = models.TextField(null=True, blank=True)
    is_verified = models.BooleanField(default=False)
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(null=True, blank=True)
    added_by = models.ForeignKey("auth_users.User", on_delete=models.SET_NULL, null=True, blank=True, related_name="user_added_by")
    updated_by = models.ForeignKey("auth_users.User", on_delete=models.SET_NULL, null=True, blank=True, related_name="user_updated_by")

    class Meta:
        ordering = ("-id", )

    objects = UserManager()

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["username"]

    def has_perm(self, perm, obj=None):
        return self.is_superuser

    def has_module_perms(self, app_label):
        return self.is_superuser

    def __str__(self):
        return self.email

    def get_user_obj_using_email(self, email):
        try:
            user_obj = User.objects.get(email=email)
        except User.DoesNotExist:
            return None
        else:
            return user_obj
        

@receiver(post_save, sender=User)
def create_user(sender, instance=None, created=False, **kwargs):
    if created:
        instance.slug = f"{shortuuid.uuid()}{instance.id}"
        instance.save(update_fields=["slug"])

home/models.py
from django.db import models

# Create your models here.

auth_users/views.py
from django.shortcuts import render
from django.views import View


class RegisterView(View):
    def get(self, request):
        return render(request, "auth_users/register.html")
        
        
class LoginView(View):
    def get(self, request):
        return render(request, "auth_users/login.html")

home/views.py
from django.shortcuts import render, redirect
from django.views import View


class HomeView(View):
    def get(self, request):
        return render(request, "home/index.html")
    

class RecentView(View):
    def get(self, request):
        return render(request, "recent/index.html")
    

class AllFilesView(View):
    def get(self, request):
        return render(request, "all_files/index.html")


class AllFoldersView(View):
    def get(self, request):
        return render(request, "all_folders/index.html")


class ProfileView(View):
    def get(self, request):
        return render(request, "profile/index.html")
    

class ImageFilesView(View):
    def get(self, request):
        return render(request, "images/index.html")
    

class VideoFilesView(View):
    def get(self, request):
        return render(request, "videos/index.html")
    

class FolderDetailView(View):
    def get(self, request, folder_slug):
        return render(request, "folder_details/index.html")
        
        
class ComparePlansView(View):
    def get(self, request):
        return render(request, "compare_plans/index.html")

auth_users/templates/auth_users/login.html
{% extends "base.html" %}

{% load static %}

{% block content %}
    {% include "components/navbar/header_sidebar.html" %}
    {% include "components/navbar/header.html" %}

    <div class="pl-[70px] pt-5 h-dvh">
        <div class="px-5 md:px-10 lg:px-20">
            <div class="flex flex-col gap-y-10">
                <h5 class="text-xl font-semibold">Sign In</h5>

                <form class="w-full mx-auto flex flex-col gap-y-5 bg-white dark:bg-stone-800 py-7 px-5 rounded-md shadow-md">
                    <div class="flex flex-col gap-y-2">
                        <label for="email" class="block text-sm font-medium text-gray-900 dark:text-white">Your Email*</label>
                        <div class="relative">
                            <div class="absolute inset-y-0 start-0 flex items-center ps-3.5 pointer-events-none">
                                <i class="fa-solid fa-at text-stone-500 dark:text-stone-400"></i>
                            </div>
                            <input type="email" id="email" class="bg-stone-50 border border-stone-300 text-stone-900 rounded-lg focus:ring-indigo-500 focus:border-indigo-500 block w-full px-10 p-2.5 dark:bg-stone-700 dark:border-stone-600 dark:placeholder-stone-400 dark:text-white dark:focus:ring-indigo-500 dark:focus:border-indigo-500" placeholder="john@example.com" />
                        </div>
                    </div>
                    <div class="flex flex-col gap-y-2">
                        <label for="password" class="block text-sm font-medium text-gray-900 dark:text-white">Your Password*</label>
                        <div class="relative">
                            <div class="absolute inset-y-0 start-0 flex items-center ps-3.5 pointer-events-none">
                                <i class="fa-solid fa-lock text-stone-500 dark:text-stone-400"></i>
                            </div>
                            <input type="password" id="password" class="bg-stone-50 border border-stone-300 text-stone-900 rounded-lg focus:ring-indigo-500 focus:border-indigo-500 block w-full px-10 p-2.5 dark:bg-stone-700 dark:border-stone-600 dark:placeholder-stone-400 dark:text-white dark:focus:ring-indigo-500 dark:focus:border-indigo-500" placeholder="******" />
                        </div>
                    </div>
                    <div>
                        <button type="submit" class="px-5 py-2 rounded-md flex items-center justify-center gap-x-2 bg-indigo-400 dark:bg-indigo-500 hover:bg-indigo-300 dark:hover:bg-indigo-400 transition-colors duration-200 ease-linear">
                            <i class="fa-solid fa-arrow-right-to-bracket"></i>
                            Login
                        </button>
                    </div>

                    <div>
                        <p class="text-center">Don't have an account? <a href="{% url 'auth_users:register' %}" class="underline text-indigo-500 dark:text-indigo-400">Sign up</a> now</p>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <script src="{% static 'js/auth_users/login.js' %}"></script>
{% endblock %}

auth_users/templates/auth_users/register.html
{% extends "base.html" %}

{% load static %}

{% block content %}
  {% include "components/navbar/header_sidebar.html" %}
  {% include "components/navbar/header.html" %}

  <div class="pl-[70px] pt-5 h-dvh">
    <div class="px-5 md:px-10 lg:px-20">
      <div class="flex flex-col gap-y-10">
        <h5 class="text-xl font-semibold">Sign Up</h5>

        <form class="w-full mx-auto flex flex-col gap-y-5 bg-white dark:bg-stone-800 py-7 px-5 rounded-md shadow-md">
          <div class="flex flex-col gap-y-2">
            <label for="username" class="block text-sm font-medium text-gray-900 dark:text-white">Your Full Name*</label>
            <div class="relative">
              <div class="absolute inset-y-0 start-0 flex items-center ps-3.5 pointer-events-none">
                <i class="fa-solid fa-circle-user text-stone-500 dark:text-stone-400"></i>
              </div>
              <input type="text" id="username" class="bg-stone-50 border border-stone-300 text-stone-900 rounded-lg focus:ring-indigo-500 focus:border-indigo-500 block w-full px-10 p-2.5 dark:bg-stone-700 dark:border-stone-600 dark:placeholder-stone-400 dark:text-white dark:focus:ring-indigo-500 dark:focus:border-indigo-500" placeholder="John" />
            </div>
          </div>
          <div class="flex flex-col gap-y-2">
            <label for="email" class="block text-sm font-medium text-gray-900 dark:text-white">Your Email*</label>
            <div class="relative">
              <div class="absolute inset-y-0 start-0 flex items-center ps-3.5 pointer-events-none">
                <i class="fa-solid fa-at text-stone-500 dark:text-stone-400"></i>
              </div>
              <input type="email" id="email" class="bg-stone-50 border border-stone-300 text-stone-900 rounded-lg focus:ring-indigo-500 focus:border-indigo-500 block w-full px-10 p-2.5 dark:bg-stone-700 dark:border-stone-600 dark:placeholder-stone-400 dark:text-white dark:focus:ring-indigo-500 dark:focus:border-indigo-500" placeholder="john@example.com" />
            </div>
          </div>
          <div class="flex flex-col gap-y-2">
            <label for="password" class="block text-sm font-medium text-gray-900 dark:text-white">Your Password*</label>
            <div class="relative">
              <div class="absolute inset-y-0 start-0 flex items-center ps-3.5 pointer-events-none">
                <i class="fa-solid fa-lock text-stone-500 dark:text-stone-400"></i>
              </div>
              <input type="password" id="password" class="bg-stone-50 border border-stone-300 text-stone-900 rounded-lg focus:ring-indigo-500 focus:border-indigo-500 block w-full px-10 p-2.5 dark:bg-stone-700 dark:border-stone-600 dark:placeholder-stone-400 dark:text-white dark:focus:ring-indigo-500 dark:focus:border-indigo-500" placeholder="******" />
            </div>
          </div>
          <div class="flex flex-col gap-y-2">
            <label for="confirm__password" class="block text-sm font-medium text-gray-900 dark:text-white">Repeat Password*</label>
            <div class="relative">
              <div class="absolute inset-y-0 start-0 flex items-center ps-3.5 pointer-events-none">
                <i class="fa-solid fa-lock text-stone-500 dark:text-stone-400"></i>
              </div>
              <input type="password" id="confirm__password" class="bg-stone-50 border border-stone-300 text-stone-900 rounded-lg focus:ring-indigo-500 focus:border-indigo-500 block w-full px-10 p-2.5 dark:bg-stone-700 dark:border-stone-600 dark:placeholder-stone-400 dark:text-white dark:focus:ring-indigo-500 dark:focus:border-indigo-500" placeholder="******" />
            </div>
          </div>
          <div>
            <button type="submit" class="px-5 py-2 rounded-md flex items-center justify-center gap-x-2 bg-indigo-400 dark:bg-indigo-500 hover:bg-indigo-300 dark:hover:bg-indigo-400 transition-colors duration-200 ease-linear">
              <i class="fa-solid fa-arrow-right-to-bracket"></i>
              Register
            </button>
          </div>

          <div>
            <p class="text-center">Already have an account! <a href="{% url 'auth_users:login' %}" class="underline text-indigo-500 dark:text-indigo-400">Sign in</a> now</p>
          </div>
        </form>
      </div>
    </div>
  </div>

  <script src="{% static 'js/auth_users/register.js' %}"></script>
{% endblock %}

home/templates/all_files/index.html
{% extends "base.html" %}

{% block content %}
    {% include "components/navbar/header_sidebar.html" %}
    {% include "components/navbar/header.html" %}
    {% include "components/file_details_preview_sidebar.html" %}

    <div class="pl-[70px] pt-5 h-dvh">
        <div class="px-5 md:px-10 lg:px-20">
            <div class="flex flex-col gap-y-10">
                {% include "./all_folders.html" %}
                {% include "./all_files.html" %}
            </div>
        </div>
    </div>
{% endblock %}

home/templates/folder_details/all_folders.html
<div class="flex flex-col gap-y-10">
    <div class="flex flex-wrap justify-between items-center gap-3">
        <nav class="flex" aria-label="Breadcrumb">
            <ol class="inline-flex items-center space-x-1 rtl:space-x-reverse">
                <li class="inline-flex items-center">
                    <a href="{% url 'home:all-folders' %}" class="font-medium inline-flex items-center gap-x-2 text-sm font-medium hover:text-indigo-500 dark:text-stone-400 dark:hover:text-stone-100">
                        <i class="fa-regular fa-folder-open text-lg"></i>
                        All Folders
                    </a>
                </li>
                <li aria-current="page">
                    <div class="flex items-center">
                        <svg class="rtl:rotate-180 w-3 h-3 text-gray-400 mx-1" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
                            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 9 4-4-4-4"/>
                        </svg>
                        <span class="ms-1 text-sm font-medium text-gray-500 md:ms-2 dark:text-gray-400">123</span>
                    </div>
                </li>
            </ol>
        </nav>
    </div>

    <div class="grid sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-5">
        <div class="w-full relative p-5 bg-white hover:bg-white/50 rounded-lg shadow-sm dark:bg-stone-800 dark:hover:bg-stone-700">
            <div class="absolute top-1 right-2">
                <button id="dropdown__folderBtn-1" data-dropdown-toggle="dropdown__folder-1" class="flex hover:bg-stone-200 dark:hover:bg-stone-800 focus:ring-4 focus:outline-none focus:ring-stone-200 dark:focus:ring-stone-700 rounded-lg p-1.5" type="button">
                    <i class="fa-solid fa-ellipsis"></i>
                </button>
                {% comment %}Dropdown menu{% endcomment %}
                <div id="dropdown__folder-1" class="z-10 hidden text-base list-none bg-white divide-y divide-stone-100 dark:divide-stone-700 rounded-lg shadow-sm border border-stone-200 dark:border-stone-700 w-44 dark:bg-stone-800">
                    <ul class="py-2" aria-labelledby="dropdown__folderBtn-1">
                        <li>
                            <button
                                data-drawer-target="file__detailPreviewSidebar" data-drawer-show="file__detailPreviewSidebar" data-drawer-placement="right" aria-controls="file__detailPreviewSidebar"
                                type="button" class="cursor-pointer w-full text-sm flex items-center gap-x-2 px-4 py-2 hover:bg-stone-100 dark:hover:bg-stone-600 dark:text-stone-200">
                                <i class="fa-solid fa-circle-info text-stone-500 dark:text-stone-400"></i>
                                Details
                            </button>
                        </li>
                        <li>
                            <button type="button" class="cursor-pointer w-full text-sm flex items-center gap-x-2 px-4 py-2 hover:bg-stone-100 dark:hover:bg-stone-600 dark:text-stone-200">
                                <i class="fa-solid fa-download text-stone-500 dark:text-stone-400"></i>
                                Download
                            </button>
                        </li>
                        <li>
                            <button type="button" class="cursor-pointer w-full text-sm flex items-center gap-x-2 px-4 py-2 hover:bg-stone-100 dark:hover:bg-stone-600 dark:text-stone-200">
                                <i class="fa-solid fa-pen text-stone-500 dark:text-stone-400"></i>
                                Rename
                            </button>
                        </li>
                    </ul>
                    <div class="py-1.5">
                        <button type="button" class="cursor-pointer w-full text-sm flex items-center gap-x-2 px-4 py-2 text-rose-500 hover:bg-stone-100 dark:hover:bg-stone-600">
                            <i class="fa-solid fa-trash-can"></i>
                            Delete
                        </button>
                    </div>
                </div>
            </div>
            <a href="#" class="flex flex-col gap-y-4">
                <i class="fa-regular fa-folder text-2xl text-stone-500 dark:text-stone-400"></i>
                <div class="flex flex-col gap-y-1">
                    <h5 class="text-base font-semibold">Documents</h5>
                    <p class="text-stone-500 dark:text-stone-400">24 files</p>
                </div>
            </a>
        </div>
        <div class="w-full relative p-5 bg-white hover:bg-white/50 rounded-lg shadow-sm dark:bg-stone-800 dark:hover:bg-stone-700">
            <div class="absolute top-1 right-2">
                <button id="dropdown__folderBtn-2" data-dropdown-toggle="dropdown__folder-2" class="flex hover:bg-stone-200 dark:hover:bg-stone-800 focus:ring-4 focus:outline-none focus:ring-stone-200 dark:focus:ring-stone-700 rounded-lg p-1.5" type="button">
                    <i class="fa-solid fa-ellipsis"></i>
                </button>
                {% comment %}Dropdown menu{% endcomment %}
                <div id="dropdown__folder-2" class="z-10 hidden text-base list-none bg-white divide-y divide-stone-100 dark:divide-stone-700 rounded-lg shadow-sm border border-stone-200 dark:border-stone-700 w-44 dark:bg-stone-800">
                    <ul class="py-2" aria-labelledby="dropdown__folderBtn-2">
                        <li>
                            <button
                                data-drawer-target="file__detailPreviewSidebar" data-drawer-show="file__detailPreviewSidebar" data-drawer-placement="right" aria-controls="file__detailPreviewSidebar"
                                type="button" class="cursor-pointer w-full text-sm flex items-center gap-x-2 px-4 py-2 hover:bg-stone-100 dark:hover:bg-stone-600 dark:text-stone-200">
                                <i class="fa-solid fa-circle-info text-stone-500 dark:text-stone-400"></i>
                                Details
                            </button>
                        </li>
                        <li>
                            <button type="button" class="cursor-pointer w-full text-sm flex items-center gap-x-2 px-4 py-2 hover:bg-stone-100 dark:hover:bg-stone-600 dark:text-stone-200">
                                <i class="fa-solid fa-download text-stone-500 dark:text-stone-400"></i>
                                Download
                            </button>
                        </li>
                        <li>
                            <button type="button" class="cursor-pointer w-full text-sm flex items-center gap-x-2 px-4 py-2 hover:bg-stone-100 dark:hover:bg-stone-600 dark:text-stone-200">
                                <i class="fa-solid fa-pen text-stone-500 dark:text-stone-400"></i>
                                Rename
                            </button>
                        </li>
                    </ul>
                    <div class="py-1.5">
                        <button type="button" class="cursor-pointer w-full text-sm flex items-center gap-x-2 px-4 py-2 text-rose-500 hover:bg-stone-100 dark:hover:bg-stone-600">
                            <i class="fa-solid fa-trash-can"></i>
                            Delete
                        </button>
                    </div>
                </div>
            </div>
            <a href="#" class="flex flex-col gap-y-4">
                <i class="fa-regular fa-folder text-2xl text-stone-500 dark:text-stone-400"></i>
                <div class="flex flex-col gap-y-1">
                    <h5 class="text-base font-semibold">Documents</h5>
                    <p class="text-stone-500 dark:text-stone-400">24 files</p>
                </div>
            </a>
        </div>
    </div>
</div>

home/templates/folder_details/index.html
{% extends "base.html" %}

{% block content %}
    {% include "components/navbar/header_sidebar.html" %}
    {% include "components/navbar/header.html" %}
    {% include "components/file_details_preview_sidebar.html" %}

    <div class="pl-[70px] pt-5 h-dvh">
        <div class="px-5 md:px-10 lg:px-20">
            <div class="flex flex-col gap-y-10">
                {% include "./all_folders.html" %}
                {% include "./all_files.html" %}
            </div>
        </div>
    </div>
{% endblock %}

home/templates/recent/index.html
{% extends "base.html" %}

{% block content %}
    {% include "components/navbar/header_sidebar.html" %}
    {% include "components/navbar/header.html" %}
    {% include "components/file_details_preview_sidebar.html" %}

    <div class="pl-[70px] pt-5 h-dvh">
        <div class="px-5 md:px-10 lg:px-20">
            <div class="flex flex-col gap-y-10">
                {% include "./recent_folders.html" %}
                {% include "./recent_files.html" %}
            </div>
        </div>
    </div>
{% endblock %}

home/templates/recent/recent.html
{% extends "base.html" %}

{% block content %}
    {% comment %}Dayjs{% endcomment %}
    <script src="https://cdn.jsdelivr.net/npm/dayjs@1/dayjs.min.js"></script>

    {% include "components/navbar/header_sidebar.html" %}
    {% include "components/navbar/header.html" %}
    <div class="pl-[70px] pt-5 h-dvh">
        <div class="px-5 md:px-10 lg:px-20">
            <div class="flex flex-col gap-y-10">
                {% include "./recent_folders.html" %}
                {% include "./recent_files.html" %}
            </div>
        </div>
    </div>
{% endblock %}

home/templates/recent/recent_folders.html
<div class="flex flex-col gap-y-10">
    <div class="flex flex-wrap justify-between items-center gap-3">
        <nav class="flex" aria-label="Breadcrumb">
            <ol class="inline-flex items-center space-x-1 md:space-x-2 rtl:space-x-reverse">
                <li aria-current="page" class="inline-flex items-center">
                    <div class="font-medium inline-flex items-center gap-x-2 text-sm font-medium hover:text-indigo-500 dark:text-stone-400 dark:hover:text-stone-100">
                        <i class="fa-regular fa-folder-open text-lg"></i>
                        All Folders
                    </div>
                </li>
            </ol>
        </nav>
        <a href="{% url 'home:all-files' %}" class="px-3 py-1.5 rounded-md flex items-center justify-center gap-x-2 bg-stone-200 dark:bg-stone-800 hover:bg-white dark:hover:bg-stone-700 transition-colors duration-200 ease-linear">
            Show All
            <i class="fa-solid fa-arrow-right-long"></i>
        </a>
    </div>

    <div class="grid sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-5">
        <div class="w-full relative p-5 bg-white hover:bg-white/50 rounded-lg shadow-sm dark:bg-stone-800 dark:hover:bg-stone-700">
            <div class="absolute top-1 right-2">
                <button id="dropdown__folderBtn-1" data-dropdown-toggle="dropdown__folder-1" class="flex hover:bg-stone-200 dark:hover:bg-stone-800 focus:ring-4 focus:outline-none focus:ring-stone-200 dark:focus:ring-stone-700 rounded-lg p-1.5" type="button">
                    <i class="fa-solid fa-ellipsis"></i>
                </button>
                {% comment %}Dropdown menu{% endcomment %}
                <div id="dropdown__folder-1" class="z-10 hidden text-base list-none bg-white divide-y divide-stone-100 dark:divide-stone-700 rounded-lg shadow-sm border border-stone-200 dark:border-stone-700 w-44 dark:bg-stone-800">
                    <ul class="py-2" aria-labelledby="dropdown__folderBtn-1">
                        <li>
                            <button
                                data-drawer-target="file__detailPreviewSidebar" data-drawer-show="file__detailPreviewSidebar" data-drawer-placement="right" aria-controls="file__detailPreviewSidebar"
                                type="button" class="cursor-pointer w-full text-sm flex items-center gap-x-2 px-4 py-2 hover:bg-stone-100 dark:hover:bg-stone-600 dark:text-stone-200">
                                <i class="fa-solid fa-circle-info text-stone-500 dark:text-stone-400"></i>
                                Details
                            </button>
                        </li>
                        <li>
                            <button type="button" class="cursor-pointer w-full text-sm flex items-center gap-x-2 px-4 py-2 hover:bg-stone-100 dark:hover:bg-stone-600 dark:text-stone-200">
                                <i class="fa-solid fa-download text-stone-500 dark:text-stone-400"></i>
                                Download
                            </button>
                        </li>
                        <li>
                            <button type="button" class="cursor-pointer w-full text-sm flex items-center gap-x-2 px-4 py-2 hover:bg-stone-100 dark:hover:bg-stone-600 dark:text-stone-200">
                                <i class="fa-solid fa-pen text-stone-500 dark:text-stone-400"></i>
                                Rename
                            </button>
                        </li>
                    </ul>
                    <div class="py-1.5">
                        <button type="button" class="cursor-pointer w-full text-sm flex items-center gap-x-2 px-4 py-2 text-rose-500 hover:bg-stone-100 dark:hover:bg-stone-600">
                            <i class="fa-solid fa-trash-can"></i>
                            Delete
                        </button>
                    </div>
                </div>
            </div>
            <a href="#" class="flex flex-col gap-y-4">
                <i class="fa-regular fa-folder text-2xl text-stone-500 dark:text-stone-400"></i>
                <div class="flex flex-col gap-y-1">
                    <h5 class="text-base font-semibold">Documents</h5>
                    <p class="text-stone-500 dark:text-stone-400">24 files</p>
                </div>
            </a>
        </div>
        <div class="w-full relative p-5 bg-white hover:bg-white/50 rounded-lg shadow-sm dark:bg-stone-800 dark:hover:bg-stone-700">
            <div class="absolute top-1 right-2">
                <button id="dropdown__folderBtn-2" data-dropdown-toggle="dropdown__folder-2" class="flex hover:bg-stone-200 dark:hover:bg-stone-800 focus:ring-4 focus:outline-none focus:ring-stone-200 dark:focus:ring-stone-700 rounded-lg p-1.5" type="button">
                    <i class="fa-solid fa-ellipsis"></i>
                </button>
                {% comment %}Dropdown menu{% endcomment %}
                <div id="dropdown__folder-2" class="z-10 hidden text-base list-none bg-white divide-y divide-stone-100 dark:divide-stone-700 rounded-lg shadow-sm border border-stone-200 dark:border-stone-700 w-44 dark:bg-stone-800">
                    <ul class="py-2" aria-labelledby="dropdown__folderBtn-2">
                        <li>
                            <button
                                data-drawer-target="file__detailPreviewSidebar" data-drawer-show="file__detailPreviewSidebar" data-drawer-placement="right" aria-controls="file__detailPreviewSidebar"
                                type="button" class="cursor-pointer w-full text-sm flex items-center gap-x-2 px-4 py-2 hover:bg-stone-100 dark:hover:bg-stone-600 dark:text-stone-200">
                                <i class="fa-solid fa-circle-info text-stone-500 dark:text-stone-400"></i>
                                Details
                            </button>
                        </li>
                        <li>
                            <button type="button" class="cursor-pointer w-full text-sm flex items-center gap-x-2 px-4 py-2 hover:bg-stone-100 dark:hover:bg-stone-600 dark:text-stone-200">
                                <i class="fa-solid fa-download text-stone-500 dark:text-stone-400"></i>
                                Download
                            </button>
                        </li>
                        <li>
                            <button type="button" class="cursor-pointer w-full text-sm flex items-center gap-x-2 px-4 py-2 hover:bg-stone-100 dark:hover:bg-stone-600 dark:text-stone-200">
                                <i class="fa-solid fa-pen text-stone-500 dark:text-stone-400"></i>
                                Rename
                            </button>
                        </li>
                    </ul>
                    <div class="py-1.5">
                        <button type="button" class="cursor-pointer w-full text-sm flex items-center gap-x-2 px-4 py-2 text-rose-500 hover:bg-stone-100 dark:hover:bg-stone-600">
                            <i class="fa-solid fa-trash-can"></i>
                            Delete
                        </button>
                    </div>
                </div>
            </div>
            <a href="#" class="flex flex-col gap-y-4">
                <i class="fa-regular fa-folder text-2xl text-stone-500 dark:text-stone-400"></i>
                <div class="flex flex-col gap-y-1">
                    <h5 class="text-base font-semibold">Documents</h5>
                    <p class="text-stone-500 dark:text-stone-400">24 files</p>
                </div>
            </a>
        </div>
    </div>
</div>

templates/components/border.html
<div class="w-full flex items-center">
    <i class="fa-solid fa-plus text-xs text-stone-400 dark:text-stone-500 text-[0.65rem]"></i>
    <div class="w-full h-[2px] bg-stone-200 dark:bg-stone-600 rounded-full"></div>
    <i class="fa-solid fa-plus text-xs text-stone-400 dark:text-stone-500 text-[0.65rem]"></i>
</div>